### ISSUE TITLE
KeyError: 'TrainingFraction'

### ISSUE THREAD

**Issue by Emma-Mar** [bf777/MesoNet#31]
Hi,

I'm able to get the GUI running, but when I click any of the quick start automated pipelines I end up with with the error: KeyError: 'TrainingFraction'. How can I fix this? Thank you!

Here is the full error:
/Users/name/MesoNet/mesonet/models/DongshengXiao_brain_bundary.hdf5
/Users/name/Test_Images
1
/Users/name/Test_Images/0.png
OpenCV: FFMPEG: tag 0x4745504d/'MPEG' is not supported with codec id 2 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
DLC config file path: /Users/name/MesoNet/mesonet/dlc/config.yaml
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/mesonet/gui_test.py", line 578, in <lambda>
    command=lambda: self.EnterThread("atlas_to_brain"),
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/mesonet/gui_test.py", line 1100, in EnterThread
    target=self.PredictDLC(
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/mesonet/gui_test.py", line 1365, in PredictDLC
    DLCPredict(
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/mesonet/dlc_predict.py", line 158, in DLCPredict
    deeplabcut.analyze_videos(
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 490, in analyze_videos
    trainFraction = cfg["TrainingFraction"][trainingsetindex]
  File "/Users/name/opt/anaconda3/envs/DEEPLABCUT/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 851, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'TrainingFraction'

**Comment by bf777** [comment]
Hi @Emma-Mar, sorry to hear that you're experiencing this issue. Could you try running `test.py` in the `tests` folder and confirm whether that is working for you? This is just to determine whether the issue is specific to the GUI or to the code as a whole - thank you!

**Comment by Emma-Mar** [comment]
Hi @bf777, thank you for your reply. When I run test.py I get a final line that says that all default MesoNet pipelines are fully functional. I have attached a pdf of the output. Thank you for your help!
[Test Output.pdf](https://github.com/bf777/MesoNet/files/13640307/Test.Output.pdf)

**Comment by bf777** [comment]
@Emma-Mar I think the issue could be related to an incorrect path to the default configuration file. I've updated the default if you want to try pulling again - some errors came up while running tests when deploying the update, but these could be keras installation quirks that may not affect your setup if the test script was working for you. Alternatively, you can also just change the path to the config file in the GUI to be:
```
/Users/name/MesoNet/mesonet/dlc/atlas-DongshengXiao-2020-08-03/config.yaml
```
(the sample data needs to be downloaded for this as per our instructions). This seems to be working on my end on MacOS. I hope this helps!

**Comment by bf777** [comment]
I am closing this issue because of inactivity.
